spring:

  datasource:

    url: jdbc:postgresql://localhost:5433/taxi
    username: postgres
    password: jiyjo@2001
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
logging:
  level:
    org.springframework: INFO


